version: '{build}'

environment:
  APPVEYOR: 1
  DEPLOY: 0

  matrix:
    # MSVC x86
    - PLATFORM: amd64_x86
      QTDIR: C:\Qt\5.10.1\msvc2015
      MAKE: nmake
      MAKEFILES: NMake Makefiles
      DEPLOY: 1

    # MSVC x64
    - PLATFORM: amd64
      QTDIR: C:\Qt\5.10.1\msvc2015_64
      MAKE: nmake
      MAKEFILES: NMake Makefiles
      DEPLOY: 1

    # MinGW
    - PLATFORM: mingw
      QTDIR: C:\Qt\5.10.1\mingw53_32
      MAKE: mingw32-make
      MAKEFILES: MinGW Makefiles

init:
  - git config --global core.autocrlf input
  - if %PLATFORM%==mingw set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %PLATFORM%==mingw set PATH=C:\Qt\Tools\mingw492_32\bin;%PATH%
  - set PATH=%QTDIR%\bin;%PATH%
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
  - if not %PLATFORM%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
  - if "%APPVEYOR_REPO_TAG%"=="true" set "ORGANIZER_VERSION=%APPVEYOR_REPO_TAG_NAME%"
  - if "%PLATFORM%"=="X86" (set "PLATFORM_NAME=x86") else (set "PLATFORM_NAME=x64")

build_script:
  # Build Organizer
  - mkdir build
  - cd build
  - cmake .. -G "%MAKEFILES%" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVERSION="%ORGANIZER_VERSION%"
  - if not %PLATFORM%==mingw (nmake) else (mingw32-make)
  - cd ..

  # Generate installer
  - if %DEPLOY%==1 if "%APPVEYOR_REPO_TAG%"=="true" iscc /Q /DMyAppVersion="%ORGANIZER_VERSION%" /DPlatformName="%PLATFORM_NAME%" /DQtDir="%QTDIR%" setup/setup.iss

  # Package symbol files to zip
  - if %DEPLOY%==1 if "%APPVEYOR_REPO_TAG%"=="true" 7z a "setup\Organizer_%ORGANIZER_VERSION%_%PLATFORM_NAME%_symbols.zip" ".\build\Organizer.pdb"

artifacts:
  - path: setup\Organizer_*.exe
    name: windows_setup
  - path: setup\Organizer_*_symbols.zip
    name: windows_symbols_zip

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    draft: true
    prerelease: false
    force_update: true
    artifact: windows_setup, windows_symbols_zip
    auth_token:
      secure: iidqLm2GI+4+noVrt0G/SGDDOPcCincYkG8tLJfYuf7y2+1BCTOhimba5LPXPk9G
    on:
      APPVEYOR_REPO_TAG: true
      DEPLOY: 1