language: cpp
compiler: gcc

# Qt packages for Linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &shared_deps
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtmultimedia5-dev
      - qttools5-dev
      - qttools5-dev-tools

# OS X build
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *shared_deps
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      dist: bionic
      sudo: required
    - os: osx

# Qt packages for OS X
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update &&
      brew install qt5 &&
      QT_PATH=$(find /usr/local/Cellar/qt/* -maxdepth 0 -type d | head -1)
      PATH=$QT_PATH/bin:$PATH &&
      export PATH
    ; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - cd ..